[DEFAULTS]
DisableDev = 1 

[INCLUDE: common/materials_glass.ini]
[Material_Glass]
Materials= EXT_TAILLIGHT_GLASS
IOR = 1.6              ; looks better like this
FilmIOR = $IOR       ; redefine IOR for external film layer to increase reflections
ThicknessMult = 2.5  ; thicker glass passes less light through
ProfileFix = 0.04    ; adds thickness to glass for glazing angles
MaskPass = 0            ; mask pass opacity
MaskPassColor = 255, 0, 0  ; mask pass color adjustment

[Material_Glass]
Meshes= EXT_HEADANDTAIL_LIGHT_GLASS
IOR = 1.460              ; looks better like this
FilmIOR = $IOR       ; redefine IOR for external film layer to increase reflections
ThicknessMult = 0  ; thicker glass passes less light through
ProfileFix = 0.04    ; adds thickness to glass for glazing angles
MaskPass = 1           ; mask pass opacity
MaskPassColor = 255, 0, 0  ; mask pass color adjustment

[Material_Glass]
Materials = EXT_GLASS
ThicknessMult = 2
EXTRA_MASK_PASS = 10
EXTRA_MASK_PASS_OPACITY = 5

[Material_PhotoelasticGlass]
Materials=EXT_HEADLIGHT_GLASS
IOR=2
FilmIOR = 2.2
PhotoelasticityMult = 1.5
ProfileFix = 0.08
ThicknessMult=0.1

;PBR EXTERIOR

[INCLUDE: common/materials_interior.ini]
[Material_Carbon]
Meshes = EXT_CARBON
BrightnessAdjustment = 0.2
ClearCoatThickness=0.1
ClearCoatF0 = 0.1
DetailNormalBlend = 1
RESOURCE_TEXTURE_0=carbon.dds
RESOURCE_TEXTURE_1=carbon_nm.dds
DetailScale = 550

[Material_Carbon]
Meshes = EXT_CARBON_BOOLEAN
BrightnessAdjustment = 0.2
ClearCoatThickness=0.1
ClearCoatF0 = 0.1
RESOURCE_TEXTURE_0=carbon.dds
RESOURCE_TEXTURE_1=carbon_nm.dds
DetailScale = 605

[Material_Plastic]
Materials= EXT_PLASTIC_GLOSSY
Smoothness = 0.8
Reflectance = 0.1
BrightnessAdjustment = 0.15

[Material_Metal_v2]
Materials=EXT_WIPERS
Metalness = 0.9
BrightnessAdjustment = 0
LocalReflectionsSharpness = 1
DetailScale= 0

[INCLUDE: common/materials_interior.ini]
[Material_InteriorPBRDetail]
Materials=EXT_RIM_PAINT, EXT_RIM_NM
Metalness=0.08
Reflectance=0.06
CubemapReflectionBlur=1.2
DetailScale=80
ApplyTilingFix=1

[Material_Metal_v2]
Materials=EXHAUST_METAL
Metalness = 0.65
DetailScale=120
BrightnessAdjustment = 0.1
DetailNormalBlend = 1
LocalReflectionsSharpness = 0.3
OcclusionMap = 0.5
CubemapReflectionBlur = 0.5

[Material_Aluminium_v2]
Materials=EXT_ALUMINUM, INT_ALUMINUM_STEERINGWHEEL
Metalness = 0.4
Reflectance = 0.1
BrightnessAdjustment = 0.5
DetailTexture = 1
DetailNormalTexture = common/pbr_metal.dds
DetailNormalPBRSecondaryColor = 0, 0, 0, 0
ApplyTilingFix=1
DetailScale = 80
DetailNormalBlend = 0.2
DetailNormalPBRSmoothnessGamma = 0.2

[Material_Glass]
Meshes=EXT_REFLECTOR_REAR
MaskPass=5
MaskPassColor=255,255,255
ThicknessMult=4.5
UseNormalMap=1

;PBR INTERIOR

[Material_Carpet_v2]
Materials=INT_CARPET
BrightnessAdjustment = 0.5
OcclusionMap = 0.65
Reflectance = 0.04
DetailScale=70

[Material_Plastic_v2]
Materials = INT_PLASTIC, INT_PLASTIC_STEERINGWHEEL
Reflectance = 0.3
Smoothness=0.8
BrightnessAdjustment = 0.55
DetailScale=50

[Material_Leather]
Materials = INT_LEATHER_STEERINGWHEEL, INT_LEATHER
BrightnessAdjustment = 0.4
DetailNormalPBRSecondaryColor = 0, 0, 0, 0.5
Smoothness = 0.3
DetailScale=100
Reflectance = 0.15

[Material_Leather]
Materials = INT_RED_LEATHER
BrightnessAdjustment = 0.9
OcclusionMap = 0.85
DetailNormalPBRSecondaryColor = 0, 0, 0, 0.5
Smoothness = 0.3
DetailScale=800
RESOURCE_0=txDetail
RESOURCE_TEXTURE_0=red leather diffuse.DDS
RESOURCE_1=txNormalDetail
RESOURCE_TEXTURE_1=red leather nm.DDS
Reflectance = 0.25

[Material_Velvet_v2]
Materials = INT_ALCANTARA_STEERINGWHEEL, INT_ALCANTARA
BrightnessAdjustment=0.55
OcclusionMap = 0.3
Reflectance = 0.1
ApplyTilingFix = 1
DetailNormalBlend = 1
DetailScale = 150
RESOURCE_0=txDetail
RESOURCE_TEXTURE_0=alcnt.dds
RESOURCE_1=txNormalDetail
RESOURCE_TEXTURE_1=alcnt_nm.dds

[Material_Velvet_v2]
Materials = INT_STEERINGWHEEL_MARKER
BrightnessAdjustment=0.7
OcclusionMap = 0.6
Reflectance = 0.1
ApplyTilingFix = 1
DetailNormalBlend = 1
DetailScale = 50
RESOURCE_0=txDetail
RESOURCE_TEXTURE_0=alcnt marker.dds
RESOURCE_1=txNormalDetail
RESOURCE_TEXTURE_1=alcnt_nm.dds

[Material_Velvet_v2]
Materials=INT_SEAT_CLOTH
BrightnessAdjustment = 1
OcclusionMap = 0.7
DetailNormalPBRSecondaryColor = 0, 0, 0, 0
UseClothShading = 1
ApplyTilingFix=1
RESOURCE_0=txDetail
RESOURCE_TEXTURE_0=seat centre diffuse
RESOURCE_1=txNormalDetail
RESOURCE_TEXTURE_1=seat centre nm.dds
Reflectance = 0.3
DetailScale = 160
ClothSheenColor = 1, 1, 1

[Material_LeatherPoked_v2]
Materials = INT_SPOTTED_LEATHER
Reflectance = 0.04
BrightnessAdjustment = 0.7
OcclusionMap = 0.7
DetailNormalTexture = common/pbr_leather_pattern.dds
DetailNormalIntensity = 2
DetailNormalPBRSecondaryColor = 0, 0, 0, 10
DetailNormalPBRReflectance = 10

[Material_Chrome]
Materials = INT_ALUMINUM, INT_STEERINGWHEEL_CHROME
BrightnessAdjustment = 0.95
OcclusionMap = 0.7
Smoothness = 0.95
Metalness = 0.85
Reflectance = 0.0
BrightnessAdjustment = 1.5
CubemapReflectionBlur = 1

[Material_Carbon]
Meshes = INT_CARBON
BrightnessAdjustment = 0.75
ClearCoatF0 = 0.15
RESOURCE_TEXTURE_0=carbon.dds
RESOURCE_TEXTURE_1=carbon_nm.dds
DetailScale = 550